management:
  server:
    port: 8081
    servlet:
      context-path: /admin

  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /monitor


info:
  app:
    project:
      name: Actuator
      language: kotlin
      devices: universal

server:
  port: 8080
  servlet:
    context-path: /api

#spring:
#  security:
#    user:
#      name: user
#      password: pass
#      roles:
#        - GUEST
#        - USER
#        - ADMIN
